name: 'Relatório de bug'
description: Crie um relatório para nos ajudar a melhorar
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um problema :pray:.

        Este rastreador de problemas é para bugs e questões encontradas no [Bolt.diy](https://bolt.diy).
        Se você encontrar problemas relacionados ao WebContainer, por favor, abra uma issue no repositório oficial [StackBlitz WebContainer](https://github.com/stackblitz/webcontainer-core).

        Quanto mais informações você preencher, melhor poderemos ajudá-lo.
  - type: textarea
    id: description
    attributes:
      label: Descreva o bug
      description: Forneça uma descrição clara e concisa do que você está encontrando.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link para a URL do Bolt que causou o erro
      description: Por favor, não a delete após reportar!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Descreva os passos que temos que seguir para reproduzir o comportamento.
      placeholder: |
        1. Vá para '...'
        2. Clique em '....'
        3. Role para baixo até '....'
        4. Veja o erro
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
      description: Forneça uma descrição clara e concisa do que você esperava que acontecesse.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Gravação de Tela / Captura de Tela
      description: Se aplicável, **por favor inclua uma gravação de tela** (preferencialmente) ou captura de tela mostrando o problema. Isso nos ajudará a resolver seu problema <u>rapidamente</u>.
  - type: textarea
    id: platform
    attributes:
      label: Plataforma
      value: |
        - Sistema Operacional: [ex: macOS, Windows, Linux]
        - Navegador: [ex: Chrome, Safari, Firefox]
        - Versão: [ex: 91.1]
  - type: input
    id: provider
    attributes:
      label: Provedor Utilizado
      description: Diga-nos qual provedor você está usando.
  - type: input
    id: model
    attributes:
      label: Modelo Utilizado
      description: Diga-nos qual modelo você está usando.
  - type: textarea
    id: additional
    attributes:
      label: Contexto adicional
      description: Adicione qualquer outro contexto sobre o problema aqui.
